name: home
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  


  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_database: ^10.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:

  fonts:
    - family: Astrella
      fonts:
      - asset: fonts/Astrella.ttf
  
    - family: Poppins
      fonts:
      - asset: fonts/Poppins.ttf
    
    - family: Poppins-Light
      fonts:
      - asset: fonts/Poppins-Light.ttf

  assets:
    - assets/
    - assets/images/


  uses-material-design: true
       
         
           
  
    
      
        

  
    
      
  
